name: Build/release
permissions: write-all

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os.name }}

    strategy:
      matrix:
        os:
          - name: macos-latest
            artefact-pattern: dist/silverkey2-*.dmg
          - name: windows-latest
            artefact-pattern: dist/silverkey2*.exe
          - name: ubuntu-latest
            artefact-pattern: dist/silverkey2-*.AppImage

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: yarn build
        run: |
          yarn dist

      - uses: actions/upload-artifact@v3
        with:
          name: silverkey2-${{ matrix.os.name }}
          path: ${{ matrix.os.artefact-pattern }}
          retention-days: 1

